/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'MarkPerry' at '10/30/15 10:13 PM' with Gradle 2.8
 *
 * @author MarkPerry, @date 10/30/15 10:13 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
